#ifndef CALCULATE_INTEGRAL_MULTIPLE_THREADS_ERRORS_H
#define CALCULATE_INTEGRAL_MULTIPLE_THREADS_ERRORS_H

#define OK 0
#define NO_CONFIG_FOUND 1
#define CANNOT_OPEN_FILE 2
#define NO_SUCH_CFG_ARG 3
#define INVALID_ARG 4

#endif //CALCULATE_INTEGRAL_MULTIPLE_THREADS_ERRORS_H
